# ============================================================================
#                        Copyright 2022 Gennaro Prota.
# ============================================================================

notes:                              "Copyright {year} Gennaro Prota."
line_width:                         78
